version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install
          command: ./scripts/ci/linux/install_codestyle.bash
      - run:
          name: Code Style
          command: ./scripts/ci/linux/codestyle.bash
