version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install
          command: sudo apt-get install -y --allow-unauthenticated astyle
      - run:
          name: Code Style
          command: ./scripts/ci/linux/codestyle.bash
