name: Backport
on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  backport:
    if: contains( join(github.event.pull_request.labels.*.name), 'backport')
    runs-on: ubuntu-18.04
    name: Backport
    steps:
      - name: Backport Bot
        uses: Gaurav0/backport@v1.0.24
        with:
          bot_username: mdal-bot
          bot_token: 54-58-55-07-00-50-55-52-0c-57-54-02-0d-52-5f-00-51-04-56-56-52-04-0b-03-51-5e-05-50-53-01-0a-56-5a-01-53-06-57-53-05-03
          bot_token_key: d9fa6c4c5c745af2ced27f8bef06f92ab3b6f1f6 
          github_token: ${{ secrets.GITHUB_TOKEN }}
