name: Code Style
on: [push, pull_request]
jobs:
  code_style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Astyle
      run: sudo apt-get install astyle
    - name: Run Astyle
      run: ./scripts/check_all.bash
