name: OSX Tests
on: [push]
env:
  QGIS_DEPS_VERSION: 0.4.0
jobs:
  osx_tests:
    if: github.repository == 'lutraconsulting/MDAL'
    runs-on: macos-latest
    steps:
      - name: Checkout MDAL
        uses: actions/checkout@v2

      - name: install deps
        run: |
          wget https://qgis.org/downloads/macos/deps/qgis-deps-${QGIS_DEPS_VERSION}.tar.gz
          sudo mkdir -p /opt/QGIS/qgis-deps-${QGIS_DEPS_VERSION}/stage/
          cd /opt/QGIS/qgis-deps-${QGIS_DEPS_VERSION}/stage/
          sudo tar -xvzf $THIS_DIR/qgis-deps-${QGIS_DEPS_VERSION}.tar.gz
          /opt/QGIS/qgis-deps-${QGIS_DEPS_VERSION}/stage/bin/gdalinfo --formats

      - name: build MDAL
        run: |
          mkdir -p ../build_osx
          cd ../build_osx
          cmake \
              -DCMAKE_BUILD_TYPE=Debug \
              -DENABLE_TESTS=ON \
              ../MDAL
          make -j`nproc`

      - name: Run tests
        env:
          CTEST_TARGET_SYSTEM: Linux-gcc
        run: |
          cd ../build_osx
          ctest -VV
